backend:
  name: git-gateway
  branch: main
  auth_endpoint: https://proklip.netlify.app/.netlify/identity

media_folder: "assets/"
public_folder: "/assets/"

collections:
  - name: "concerts"
    label: "Концерты"
    files:
      - name: "concerts"
        label: "Список концертов"
        file: "data/concerts.json"
        format: "json"
        fields:
          - label: "Концерты"
            name: "concerts"
            widget: "list"
            fields:
              - { name: "title", label: "Название", widget: "string" }
              - { name: "date", label: "Дата и время", widget: "datetime" }
              - { name: "location", label: "Место проведения", widget: "string" }
              - { name: "image", label: "Афиша", widget: "image" }
              - { name: "registrationLink", label: "Ссылка на регистрацию", widget: "string", required: false }

  - name: "lectures"
    label: "Лекции"
    files:
      - name: "lectures"
        label: "Список лекций"
        file: "data/lectures.json"
        format: "json"
        fields:
          - label: "Лекции"
            name: "lectures"
            widget: "list"
            fields:
              - { name: "title", label: "Название", widget: "string" }
              - { name: "description", label: "Описание", widget: "text" }
              - { name: "date", label: "Дата и время", widget: "datetime" }
              - { name: "image", label: "Обложка", widget: "image" }
              - { name: "registrationLink", label: "Ссылка на регистрацию", widget: "string", required: false }

  - name: "clips"
    label: "Клипы"
    files:
      - name: "clips"
        label: "Список клипов"
        file: "data/clips.json"
        format: "json"
        fields:
          - label: "Клипы"
            name: "clips"
            widget: "list"
            fields:
              - { name: "title", label: "Название", widget: "string" }
              - { name: "artist", label: "Исполнитель", widget: "string" }
              - { name: "views", label: "Просмотры", widget: "string" }
              - { name: "image", label: "Превью", widget: "image" }
              - { name: "videoLink", label: "Ссылка на видео", widget: "string" }
