backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "test"
    label: "Тестовая коллекция"
    folder: "data/test"
    fields:
      - { name: "title", label: "Тестовый заголовок", widget: "string" }