backend:
  name: git-gateway
  branch: main
  auth_endpoint: https://proklip.netlify.app/.netlify/identity

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - label: "Шоу"
    name: "concerts"
    files:
      - label: "Список мероприятий"
        name: "concerts"
        file: "data/concerts.json"
        format: "json"
        fields:
          - label: "Шоу"
            name: "concerts"
            widget: "list"
            summary: "{{title}} — {{date}}"
            fields:
              - { label: "Название", name: "title", widget: "string" }
              - { 
                  label: "Тип мероприятия", 
                  name: "type", 
                  widget: "select", 
                  options: ["Концерт", "Тусовка",],
                  default: "Концерт"
                }
              - { label: "Дата и время", name: "date", widget: "datetime" }
              - { label: "Место проведения", name: "location", widget: "string" }
              - { label: "Афиша", name: "image", widget: "image" }
              - { 
                  label: "Цена (только для тусовок, ₽)", 
                  name: "price", 
                  widget: "number", 
                  required: false,
                  hint: "Укажите цену, если это платное мероприятие" 
                }
              - { 
                  label: "Ссылка на регистрацию", 
                  hint: "Если ссылка не указана: регистрация не доступна",
                  name: "registrationLink", 
                  widget: "string", 
                  required: false 
                }

  - label: "Лекции"
    name: "lectures"
    files:
      - label: "Список лекций"
        name: "lectures"
        file: "data/lectures.json"
        format: "json"
        fields:
          - label: "Лекции"
            name: "lectures"
            widget: "list"
            summary: "{{title}} — {{date}}"
            fields:
              - { label: "Название", name: "title", widget: "string" }
              - { label: "Описание", name: "description", widget: "text" }
              - { label: "Дата и время", name: "date", widget: "datetime" }
              - { label: "Обложка", name: "image", widget: "image" }
              - { label: "Цена (₽)", name: "price", widget: "number", required: false }
              - { label: "Ссылка на регистрацию", hint: "Если ссылка не указана: регистрация не доступна", name: "registrationLink", widget: "string", required: false }

  - label: "Клипы"
    name: "clips"
    files:
      - label: "Список клипов"
        name: "clips"
        file: "data/clips.json"
        format: "json"
        fields:
          - label: "Клипы"
            name: "clips"
            widget: "list"
            summary: "{{title}} — {{artist}}"
            fields:
              - { label: "Название", name: "title", widget: "string" }
              - { label: "Исполнитель", name: "artist", widget: "string" }
              - { label: "Просмотры", name: "views", widget: "string" }
              - { label: "Превью", name: "image", widget: "image" }
              - {
                  label: "Ссылка на видео",
                  name: "videoLink",
                  widget: "string",
                }

  - label: "Главные мероприятия"
    name: "featured"
    files:
      - label: "Выбор главных мероприятий"
        name: "featured"
        file: "data/featured.json"
        format: "json"
        fields:
          - label: "Главные мероприятия"
            name: "featured"
            widget: "list"
            summary: "{{type}} - {{title}}"
            fields:
              - {
                  label: "Тип",
                  name: "type",
                  widget: "select",
                  options: ["clip", "lecture", "concert"],
                }
              - { label: "Название", name: "title", widget: "string" }
              - {
                  label: "Исполнитель/Лектор",
                  name: "artist",
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Дата",
                  name: "date",
                  widget: "datetime",
                  required: false,
                }
              - { label: "Изображение", name: "image", widget: "image" }
              - { label: "Ссылка", name: "link", widget: "string" }

  - label: "Открытие PROКЛИП"
    name: "opening"
    files:
      - label: "Контент открытия"
        name: "opening"
        file: "data/opening.json"
        format: "json"
        fields:
          - { label: "Заголовок секции", name: "title", widget: "string" }
          - label: "Галерея"
            name: "gallery"
            widget: "list"
            field: { label: "Изображение", name: "", widget: "image" }  # просто список изображений, без alt
          - label: "Видео"
            name: "video"
            widget: "object"
            fields:
              - { label: "Превью", name: "preview", widget: "image" }
              - { label: "Заголовок", name: "title", widget: "string" }
              - { label: "Авторы", name: "artists", widget: "string" }
              - { label: "Просмотры", name: "views", widget: "string" }
              - { label: "Ссылка", name: "videoLink", widget: "string" }

  - name: "posts"
    label: "Посты"
    files:
      - file: "data/posts.json"
        label: "Все посты"
        name: "posts"
        fields:
          - label: "Посты"
            name: "posts"
            widget: "list"
            summary: "{{fields.title}} ({{fields.date}})"
            fields:
              - { label: "Заголовок", name: "title", widget: "string" }
              - { label: "Дата публикации", name: "date", widget: "datetime" }
              - {
                  label: "Изображения",
                  name: "images",
                  widget: "list",
                  field: { label: "Изображение", name: "image", widget: "image" }
                }
              - { label: "Краткое описание", name: "excerpt", widget: "text" }
              - { label: "Полный текст", name: "body", widget: "markdown" }
              - {
                  label: "Slug (URL-адрес)",
                  name: "slug",
                  widget: "string",
                  hint: "Уникальная часть URL для этого поста (например: 'moj-post')"
                }